package com.dipu.primaryaccounting.model;
// Generated Nov 20, 2018 3:22:38 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * UserRole generated by hbm2java
 */
@Entity

public class UserRole implements java.io.Serializable {

    @Id
    private String emailid;
    @Column
    private String role = "ROLE_ADMIN";
    @Column
    private String status = "True";
    @Column
    private String password;

    public String getEmailid() {
        return emailid;
    }

    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

   
}
